from src.stages.crane import Crane

crane = Crane("192.168.137.93")
crane.calibrate()
crane.takeFromSortingCenter(1)
crane.putInStorage()
crane.takeFromStorage()
crane.putInPaintingCenter()
crane.takeFromSortingCenter(2)
crane.putInStorage()
crane.takeFromStorage()
crane.putInPaintingCenter()
crane.takeFromSortingCenter(3)
crane.putInStorage()
crane.takeFromStorage()
crane.putInPaintingCenter()
